[project]

name = "medseg"
version = "0.0.1"
requires-python = ">= 3.9"
dependencies = [
  "torch",
]

[build-system]

requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]

testpaths = [
  "tests",
]
addopts = [
  "--import-mode=importlib",
]
